#!/bin/sh

APP=gimp

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-i686.AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
VERSION=$(wget -q https://ppa.launchpadcontent.net/savoury1/gimp/ubuntu/pool/main/g/gimp/ -O - | grep "gimp_" | grep "18.04" | sort -u | head -1 | cut -d '"' -f 8 | grep -o -P '(?<=gimp_).*(?=.sav)')
echo "app: gimp
binpatch: true

ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu bionic-security main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main universe restricted multiverse
  ppas:
    - savoury1/ffmpeg4
    - savoury1/gimp
    - savoury1/graphics
    - savoury1/multimedia
    - savoury1/build-tools
    - savoury1/backports
  packages:
    - gimp
    - gimp-data
    - gimp-data-extras
    - gimp-help-common" >> recipe.yml;

ARCH=i386 ./pkg2appimage ./recipe.yml;

rm -R -f ./$APP/$APP.AppDir/AppRun
wget https://raw.githubusercontent.com/ivan-hc/GIMP-appimage/main/AppRun -P ./$APP/$APP.AppDir/
sed -i 's/x86_64/i386/g' ./$APP/$APP.AppDir/AppRun
sed -i 's/64/x32/g' ./$APP/$APP.AppDir/AppRun
chmod a+x ./$APP/$APP.AppDir/AppRun

# ..IMPORT THE DESKTOP FILE TO THE ROOT OF THE APPDIR...
cp ./$APP/$APP.AppDir/usr/share/applications/*$APP* ./$APP/$APP.AppDir/$APP.desktop

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir
cd ..
mv ./tmp/*.AppImage ./GNU-Image-Manipulation-Program_"$VERSION"-x86_64.AppImage 
