name: Chromium Web Browser
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 14 * * 0-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install libfuse2 libfuse2:i386 libc6:i386 libncurses5:i386 libstdc++6:i386
        sudo apt install binutils-multiarch podman qemu qemu-user-static binfmt-support
        wget -qO- https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
        distrobox create --name debian32 --image docker.io/library/debian:stable-backports i386
        distrobox-enter debian32 -- sudo apt update && sudo apt dist-upgrade
        distrobox-enter debian32 -- sudo apt install binutils coreutils curl sed wget        
        wget https://raw.githubusercontent.com/ivan-hc/32-bit-AppImage-packages-database/main/chromium
        chmod a+x ./chromium
        distrobox-enter debian32 -- ./chromium
        mkdir dist
        mv *AppImage dist/
    - uses: gautamkrishnar/keepalive-workflow@v1
      with:
        gh_token: ${{ secrets.GH_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Chromium-Web-Browser-i386.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: Chromium-Web-Browser-i386.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Chromium
            automatic_release_tag: chromium
            prerelease: false
            draft: false
            files: |
              Chromium-Web-Browser-i386.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
